apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "signal-intel-platform.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresql.password | b64enc }}
  API_KEY: {{ .Values.secrets.apiKey.value | b64enc }}
